spring:
  application:
    name: aws-advanced-jdbc-wrapper-demo
logging:  
  level:  
    software.amazon.jdbc: INFO
  file:
    name: logs/app.log
custom:
  datasource:
    host: ${DB_HOST:localhost}
    database: test
    username: root
    password: password
