spring:
  application:
    name: aws-advanced-jdbc-wrapper-demo
logging:  
  level:  
    software.amazon.jdbc: TRACE
  file:
    name: logs/app.log
custom:
  datasource:
    url: TODO:
    database: test
    username: root
    password: pass
